name: "AK-Mirror Action Deploy"

on:
  push:
  workflow_dispatch:
    
jobs:
  # 1st job for running bot 1
  bot-1:
    runs-on: ubuntu-latest

    steps:
       - name: "Checkout AK-Mirror"
         uses: actions/checkout@main
       
       - name: "Cancel Duplicate Runs"
         uses: styfle/cancel-workflow-action@0.9.0
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: "Initialize AK-Mirror"
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GIT_NAME }}
           git config --global user.email ${{ secrets.GIT_EMAIL }}
           git config --global credential.helper store
           echo "https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials
       
       # Cleanup The Actions Workspace Using Custom Composite Run Actions
       - uses: rokibhasansagar/slimhub_actions@main
       
       - name: "Clone Repository"
         continue-on-error: true
         run: |
           git clone https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.BOT_REPO }} akmirror
       - name: "Running AK-Mirror"
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd akmirror
           docker build . -t akmirror
           docker run --env CONFIG_FILE_URL=${{ secrets.CONFIG_FILE_URL1 }} akmirror
 
  # 2nd job for running bot 2
  bot-2:
    runs-on: ubuntu-latest
  
    steps:
       - name: "Checkout AK-Mirror"
         uses: actions/checkout@main
       
       - name: "Cancel Duplicate Runs"
         uses: styfle/cancel-workflow-action@0.9.0
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: "Initialize AK-Mirror"
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GIT_NAME }}
           git config --global user.email ${{ secrets.GIT_EMAIL }}
           git config --global credential.helper store
           echo "https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials
       
       # Cleanup The Actions Workspace Using Custom Composite Run Actions
       - uses: rokibhasansagar/slimhub_actions@main
       
       - name: "Clone Repository"
         continue-on-error: true
         run: |
           git clone https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.BOT_REPO }} akmirror
       - name: "Running AK-Mirror"
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd akmirror
           docker build . -t akmirror
           docker run --env CONFIG_FILE_URL=${{ secrets.CONFIG_FILE_URL2 }} akmirror

  # 3rd Job for looping the workflow after job 1 & 2 completes
  rerunner:
    needs: [bot-1, bot-2]
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main
       - name: Set Git Configs & Secrets
         run: |
           git config --global user.email ${{ secrets.GIT_EMAIL }}
           git config --global user.name ${{ secrets.GIT_NAME }}
           git config --global credential.helper store
           echo "https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials
       - name: "Re-Run AK-Mirror"
         continue-on-error: true
         run: |
           git clone https://github.com/${GITHUB_REPOSITORY} loop
           cd loop || exit 1
           echo $(date -u +%T%P) >> loop.txt
           git add loop.txt
           git commit -m "AK-Mirror : Re-Run $(date -u +%D-%T%P)"
           git push -q https://${{ secrets.GIT_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
